### ISSUE TITLE
Cannot always scroll to the bottom of vendor list

### ISSUE THREAD

**Issue by ccabanero** [spatialdev/react-seafood#21]
Browser: mobile safari iOS 11.4

Repeat: open vendor list, scroll to bottom, release, try to scroll to bottom again ...

See screenshots:
![5fb6f3bd-1f25-49e4-985e-d1e85b7acb5e](https://user-images.githubusercontent.com/1209057/42530752-d427e7a4-8436-11e8-81e8-bfae54727859.png)
![5a458bf8-d239-42aa-acc7-c9a77cc026f8](https://user-images.githubusercontent.com/1209057/42530753-d44a553c-8436-11e8-97d9-ba4590d1822c.png)

**Comment by danielduhh** [comment]
Nice - thank you, Safari right ? @ccabanero
