### ISSUE TITLE
highlighting of map pins

### ISSUE THREAD

**Issue by Naomi77Paris** [spatialdev/react-seafood#30]
Can we have another style of highlighting the map pins. Currently they become a bit transparent, which makes them look less visible but we actually want the map pin to stand out. perhaps have map pin have yellow outerglow with yellow stroke? (see attached screengrab)
<img width="373" alt="screen shot 2018-07-12 at 4 07 40 pm" src="https://user-images.githubusercontent.com/5613307/42664084-c84a9126-85ed-11e8-896e-94ca3a9b0a5a.png">

**Comment by danielduhh** [comment]
There isn't a "glow" option in Mapbox Studio, so we would need new pin svgs for each color that have the yellow glow. I could then toggle the glow layer for an individual pin when clicked

**Comment by Naomi77Paris** [comment]
Here are the icons highlighted
[icon_highlight.zip](https://github.com/spatialdev/react-seafood/files/2190632/icon_highlight.zip)

**Comment by danielduhh** [comment]
<img width="270" alt="Screen Shot 2019-07-03 at 9 01 35 AM" src="https://user-images.githubusercontent.com/1947857/60606966-2c344880-9d71-11e9-8d69-8cbd5c65296e.png">
This has been fixed. Map become opaque when selected
