### ISSUE TITLE
Game Plank stars have same information (pop up)

### ISSUE THREAD

**Issue by Naomi77Paris** [spatialdev/react-seafood#32]
Maybe we have just one star in the middle of the Game Plank vector for the information about the game plank (since it's currently redundant).

**Comment by danielduhh** [comment]
I can make the stars generic as the food vendor map pins; On click will just show the vendor name and type

**Comment by Naomi77Paris** [comment]
That’s cool. So each star will have the actual name of what it represents?

[https://htmlsigs.s3.amazonaws.com/logos/files/000/460/797/landscape/SD_logo.png] <https://htmlsig.com/t/000001BP0ERZ>

Naomi Menahem / Creative Director

2208 NW Market St #202 Seattle, WA 98107
www.spatialdev.com<https://htmlsig.com/t/000001BP0ERZ>

[Twitter] <https://htmlsig.com/t/000001BN668Z>  [Facebook]  <https://htmlsig.com/t/000001BEPMK3>  [LinkedIn]  <https://htmlsig.com/t/000001BP6P56>  [Github]  <https://htmlsig.com/t/000001BJKFHG>

On Jul 12, 2018, at 4:14 PM, Daniel B <notifications@github.com<mailto:notifications@github.com>> wrote:


I can make the stars generic as the food vendor map pins; On click will just show the vendor name and type

**Comment by danielduhh** [comment]
Each star shows its name and type; They also have the generic game plank info below
