### ISSUE TITLE
change A/C title of tab to Arts&Crafts

### ISSUE THREAD

**Issue by Naomi77Paris** [spatialdev/react-seafood#33]
Can we perhaps put this on 2 lines "Arts" on one line and "Crafts" on another?
We should get rid of A/C since it means "airconditioning"

**Comment by danielduhh** [comment]
![screen shot 2018-07-12 at 6 57 43 pm](https://user-images.githubusercontent.com/1947857/42668430-7b122f96-8605-11e8-8028-37b8408da2fe.png)

@Naomi77Paris how's that look ?

**Comment by Naomi77Paris** [comment]
Yes please!

On Jul 12, 2018, at 6:58 PM, Daniel B <notifications@github.com<mailto:notifications@github.com>> wrote:


[screen shot 2018-07-12 at 6 57 43 pm]<https://user-images.githubusercontent.com/1947857/42668430-7b122f96-8605-11e8-8028-37b8408da2fe.png>

@Naomi77Paris<https://github.com/Naomi77Paris> how's that look ?
