### ISSUE TITLE
2019 data refresh

### ISSUE THREAD

**Issue by danielduhh** [spatialdev/react-seafood#48]
Using the latest data from Devin, create both the entertainment polygons, and the vendor markers for the festival.

This latest data as of 7/3/19:
[2019SFFdata.zip](https://github.com/spatialdev/react-seafood/files/3355799/2019SFFdata.zip)

**Comment by danielduhh** [comment]
Some outstanding items:

`polygons2019_v1_0622.json` has points, and no polygons (beer garden etc, fest-bowl, etc)

### Missing from polygons2019_v1
 - beer garden
 - Amusements on Demand Face Painting
 - Kid's Deck Main Stage
 - Festi-Bowl
 - Parachutes
 - Info booth (confirm location with Devin)
 - Token Sales (confirm location wtih Devin)

 ### Need to remove (Double check with Devin)
 - No lutefisk contest?. Need to remove

### Left panel call outs
"Giant slide" -> "left_panel": true

#### Also, here's the TODO list from #45 

- [ ] Removing old 2018 booth vendor names and descriptions from point file
- [ ] Clean up general spelling and grammar of attribute tables, as applicable
- [ ] Confirm conflicting booth vendor names between vendor list and master map (see Stephen's post in festival-hackathon Slack channel, dated 06/22 at 5:42 PM PST and Devin's response that same night)
- [ ] Confirm point exists for Lutefisk Contest is included in point file (and coordinate with developers to have this point only visible on Saturday)
- [ ] Sanity check on locations of points and polygons based on master map
- [ ] Update point and polygon files based on second iteration of vendor list and master map

**Comment by stephencerqueira** [comment]
Completed tasks called out above. To publish final copy of point, polygon, and polygon centroid geojson files in coming days.
