### ISSUE TITLE
Browser display issue: Mobile Safari - bottom drawer close icon is not showing

### ISSUE THREAD

**Issue by ccabanero** [spatialdev/react-seafood#52]
In Mobile Safari, when the bottom drawer is opened the 'close icon' is not displaying.  See screenshot below:

![IMG_17804B7CC7A5-1](https://user-images.githubusercontent.com/1209057/60738327-d26b8400-9f12-11e9-8bd9-0474d466ba0f.jpeg)

**Comment by danielduhh** [comment]
Fixed by https://github.com/spatialdev/react-seafood/pull/54
